version: '2.5.0'
services:
  api:
    build: .
    container_name: currency-exchange-rates_api
    ports:
      - 5001:5001
    working_dir: /app
    command: dev
    volumes:
      - ./lib:/app/lib
      - ./src:/app/src
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456

  redis:
    image: redis:7.0.12-alpine
    container_name: currency-exchange-rates_redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass 123456
    volumes:
      - ./.redis:/data
    restart: always

volumes:
  redis:
    driver: local
